require("libraries/utils/common")
require("libraries/utils/data_structure")
require( "libraries/utils/talent" )
require( "libraries/utils/modifier" )
require("libraries/utils/ability")

-- Addon Game Mode:
LinkLuaModifier( "modifier_bonus_room_start", "modifiers/modifier_bonus_room_start", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_morty_leash", "modifiers/modifier_morty_leash", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_provides_fow_position", "modifiers/modifier_provides_fow_position", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sand_king_boss_caustic_finale", "modifiers/creatures/modifier_sand_king_boss_caustic_finale", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_breakable_container", "modifiers/modifier_breakable_container", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_boss_intro", "modifiers/modifier_boss_intro", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_attack_speed_unslowable", "modifiers/modifier_attack_speed_unslowable", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_move_speed_unslowable", "modifiers/modifier_move_speed_unslowable", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sniper_big_game_hunter_limiter", "modifiers/modifier_sniper_big_game_hunter_limiter", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_npc_dialog", "modifiers/modifier_npc_dialog", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_npc_dialog_notify", "modifiers/modifier_npc_dialog_notify", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_trap_room_player", "modifiers/traps/heroes/modifier_trap_room_player", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_player_disabled", "modifiers/modifier_player_disabled", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_aghslab_monkey_king_boundless_strike_cast", "modifiers/creatures/modifier_aghslab_monkey_king_boundless_strike_cast", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_aghslab_monkey_king_primal_spring_cast", "modifiers/creatures/modifier_aghslab_monkey_king_primal_spring_cast", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_boss_tinker_laser_burn_thinker", "modifiers/creatures/modifier_boss_tinker_laser_burn_thinker", LUA_MODIFIER_MOTION_NONE ) -- Boss Tinker's Laser ability uses both C++ and Lua, might clean it up later
LinkLuaModifier( "modifier_boss_tinker_laser_burn_debuff", "modifiers/creatures/modifier_boss_tinker_laser_burn_debuff", LUA_MODIFIER_MOTION_NONE ) -- Boss Tinker's Laser ability uses both C++ and Lua, might clean it up later
LinkLuaModifier( "modifier_hero_ambient_effects", "modifiers/modifier_hero_ambient_effects", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_announcer_ontakedamage", "modifiers/modifier_announcer_ontakedamage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_rescued_unit", "modifiers/modifier_rescued_unit", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_return_to_hub", "modifiers/modifier_return_to_hub", LUA_MODIFIER_MOTION_BOTH )

--Events:
LinkLuaModifier( "modifier_battle_royale", "modifiers/modifier_battle_royale", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_respawn_haste", "modifiers/modifier_respawn_haste", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_minor_ability_upgrades", "modifiers/modifier_minor_ability_upgrades", LUA_MODIFIER_MOTION_NONE )

--Ascension Levels:
LinkLuaModifier( "modifier_ascension_firefly_display", "modifiers/modifier_ascension_firefly_display", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ascension_last_stand_display", "modifiers/modifier_ascension_last_stand_display", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ascension_silence_display", "modifiers/modifier_ascension_silence_display", LUA_MODIFIER_MOTION_NONE )

--Blessings
LinkLuaModifier( "modifier_blessing_bottle_upgrade", "modifiers/modifier_blessing_bottle_upgrade", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_armor", "modifiers/modifier_blessing_armor", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_attack_speed", "modifiers/modifier_blessing_attack_speed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_evasion", "modifiers/modifier_blessing_evasion", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_mana_boost", "modifiers/modifier_blessing_mana_boost", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_health_boost", "modifiers/modifier_blessing_health_boost", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_magic_resist", "modifiers/modifier_blessing_magic_resist", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_magic_damage_bonus", "modifiers/modifier_blessing_magic_damage_bonus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_damage_bonus", "modifiers/modifier_blessing_damage_bonus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_movement_speed", "modifiers/modifier_blessing_movement_speed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_damage_reflect", "modifiers/modifier_blessing_damage_reflect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_spell_life_steal", "modifiers/modifier_blessing_spell_life_steal", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_life_steal", "modifiers/modifier_blessing_life_steal", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_arcanist", "modifiers/modifier_blessing_potion_arcanist", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_dragon", "modifiers/modifier_blessing_potion_dragon", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_echo_slam", "modifiers/modifier_blessing_potion_echo_slam", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_torrent", "modifiers/modifier_blessing_potion_torrent", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_shadow_wave", "modifiers/modifier_blessing_potion_shadow_wave", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_ravage", "modifiers/modifier_blessing_potion_ravage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_purification", "modifiers/modifier_blessing_potion_purification", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_respawn_time_reduction", "modifiers/modifier_blessing_respawn_time_reduction", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_respawn_invulnerability", "modifiers/modifier_blessing_respawn_invulnerability", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_death_detonation", "modifiers/modifier_blessing_death_detonation", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_strength", "modifiers/modifier_blessing_strength", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_agility", "modifiers/modifier_blessing_agility", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_intelligence", "modifiers/modifier_blessing_intelligence", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_health", "modifiers/modifier_blessing_potion_health", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_potion_mana", "modifiers/modifier_blessing_potion_mana", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_restore_mana", "modifiers/modifier_blessing_restore_mana", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_book_strength", "modifiers/modifier_blessing_book_strength", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_book_agility", "modifiers/modifier_blessing_book_agility", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_book_intelligence", "modifiers/modifier_blessing_book_intelligence", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_refresher_shard", "modifiers/modifier_blessing_refresher_shard", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_bottle_regen_duration", "modifiers/modifier_blessing_bottle_regen_duration", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_bottle_regen_movement_speed", "modifiers/modifier_blessing_bottle_regen_movement_speed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_roshan_shop_discount", "modifiers/modifier_blessing_roshan_shop_discount", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_oracle_shop_discount", "modifiers/modifier_blessing_oracle_shop_discount", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_respawn_haste", "modifiers/modifier_blessing_respawn_haste", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_respawn_attack_speed", "modifiers/modifier_blessing_respawn_attack_speed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_upgrade_reroll", "modifiers/modifier_blessing_upgrade_reroll", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_elite_shard_upgrade", "modifiers/modifier_blessing_elite_shard_upgrade", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_boss_tome", "modifiers/modifier_blessing_boss_tome", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blessing_extra_life", "modifiers/modifier_blessing_extra_life", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_blessing_attack_range", "modifiers/modifier_blessing_attack_range", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_blessing_projectile_speed", "modifiers/modifier_blessing_projectile_speed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_blessing_cast_range", "modifiers/modifier_blessing_cast_range", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_blessing_damage_on_stunned", "modifiers/modifier_blessing_damage_on_stunned", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_low_hp_outgoing_damage", "modifiers/modifier_low_hp_outgoing_damage", LUA_MODIFIER_MOTION_NONE)

--Map Encounter
LinkLuaModifier( "modifier_monster_leash", "modifiers/modifier_monster_leash", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_passive_autocast", "modifiers/modifier_passive_autocast", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ability_cast_warning", "modifiers/modifier_ability_cast_warning", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ascension_plasma_field_display", "modifiers/modifier_ascension_plasma_field_display", LUA_MODIFIER_MOTION_NONE )

--AI
LinkLuaModifier( "modifier_drow_ranger_skeleton_archer", "modifiers/creatures/modifier_drow_ranger_skeleton_archer", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ice_boss_passive", "modifiers/creatures/modifier_ice_boss_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_shroomling_enrage", "modifiers/creatures/modifier_shroomling_enrage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_shroomling_sleep", "modifiers/creatures/modifier_shroomling_sleep", LUA_MODIFIER_MOTION_NONE )

--Encounters
LinkLuaModifier( "modifier_morty_start_passive", "modifiers/creatures/modifier_morty_start_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ride_morty", "modifiers/modifier_ride_morty", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier( "modifier_pango_bonus", "modifiers/modifier_pango_bonus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_room_monster_sleep", "modifiers/modifier_room_monster_sleep", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_hoodwink_start_passive", "modifiers/creatures/modifier_bonus_hoodwink_start_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_hoodwink_passive", "modifiers/creatures/modifier_bonus_hoodwink_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_hoodwink_swallow", "modifiers/modifier_bonus_hoodwink_swallow", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_balloon_gold", "modifiers/creatures/modifier_bonus_balloon_gold", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_pudge_start_passive", "modifiers/creatures/modifier_bonus_pudge_start_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_pudge_passive", "modifiers/creatures/modifier_bonus_pudge_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_pudge_swallow", "modifiers/modifier_bonus_pudge_swallow", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_fish_gold", "modifiers/creatures/modifier_bonus_fish_gold", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_mango_orchard_mute", "modifiers/modifier_mango_orchard_mute", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_ogre_passive", "modifiers/creatures/modifier_bonus_ogre_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_ogre_start_passive", "modifiers/creatures/modifier_bonus_ogre_start_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bonus_ogre_swallow", "modifiers/modifier_bonus_ogre_swallow", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_boss_dark_willow_fear_movement_speed", "modifiers/creatures/modifier_boss_dark_willow_fear_movement_speed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_boss_dark_willow_shadow_realm_debuff", "modifiers/creatures/modifier_boss_dark_willow_shadow_realm_debuff", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_aghanim_animation_activity_modifier", "modifiers/creatures/modifier_aghanim_animation_activity_modifier", LUA_MODIFIER_MOTION_VERTICAL )
LinkLuaModifier( "modifier_morty_start_passive", "modifiers/creatures/modifier_morty_start_passive", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ride_morty", "modifiers/modifier_ride_morty", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier( "modifier_polarity", "modifiers/creatures/modifier_polarity", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_primal_beast_outro_aura", "modifiers/creatures/modifier_primal_beast_outro_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_primal_beast_outro_aura_effect", "modifiers/creatures/modifier_primal_beast_outro_aura_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_primal_beast_cinematic_controller", "modifiers/creatures/modifier_primal_beast_cinematic_controller", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_aghanim_clone", "modifiers/creatures/modifier_aghanim_clone", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_aghanim_clone_portal_out", "modifiers/creatures/modifier_aghanim_clone_portal_out", LUA_MODIFIER_MOTION_VERTICAL )
LinkLuaModifier( "modifier_rooted_unpurgable", "modifiers/creatures/modifier_rooted_unpurgable", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_rooted_unpurgable", "modifiers/creatures/modifier_rooted_unpurgable", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_restorative_flower_thinker", "modifiers/creatures/modifier_restorative_flower_thinker", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_big_tiny_grow", "modifiers/events/modifier_event_big_tiny_grow", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_doom_regen_reduction", "modifiers/events/modifier_event_doom_regen_reduction", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_leshrac_no_heal", "modifiers/events/modifier_event_leshrac_no_heal", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_leshrac_spell_lifesteal", "modifiers/events/modifier_event_leshrac_spell_lifesteal", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_leshrac_pulse_nova", "modifiers/events/modifier_event_leshrac_pulse_nova", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_leshrac_pulse_nova_recreate", "modifiers/events/modifier_event_leshrac_pulse_nova_recreate", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_leshrac_pulse_nova_activated", "modifiers/events/modifier_event_leshrac_pulse_nova_activated", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_morphling_event_attribute_shift", "modifiers/events/modifier_morphling_event_attribute_shift", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_necrophos_life_cost", "modifiers/events/modifier_event_necrophos_life_cost", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_ogre_magi_casino_bloodlust", "modifiers/events/modifier_event_ogre_magi_casino_bloodlust", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_slark_greed", "modifiers/events/modifier_event_slark_greed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_small_tiny_shrink", "modifiers/events/modifier_event_small_tiny_shrink", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_tinker_event_range_retrofit", "modifiers/events/modifier_tinker_event_range_retrofit", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_zeus_spell_amp", "modifiers/events/modifier_event_zeus_spell_amp", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_zeus_magic_resist", "modifiers/events/modifier_event_zeus_magic_resist", LUA_MODIFIER_MOTION_NONE )

